### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by KseniiaPelykh** [LoChef23/IMEMOI#55]
@LoChef23 

- Configure dev and prod gmail and set username and password on heroku.
- Send subscribe and order confirmation email to real users
- Put in CCN Margherita and Giulio

**Comment by LoChef23** [comment]
Configure dev and prod gmail and set username and password on heroku --> done

**Comment by LoChef23** [comment]
Configure dev and prod gmail and set username and password on heroku. --> done
Send subscribe and order confirmation email to real users --> done
